import { Router, Request, Response } from 'express';

const router = Router();

// AI Analysis interfaces
interface AIAnalysis {
  fundamentalBias: string;
  technicalBias: string;
  plan: string;
  riskWarning: string;
  entryZone: string;
  stopLoss: string;
  takeProfit: string;
  marketContext: string;
}

// Get API keys from environment (after dotenv.config())
// Check multiple possible env var names for flexibility
const KIMI_API_KEY = process.env.KIMI_API_KEY || process.env.VITE_KIMI_API_KEY || process.env.kimi_api_key || '';
const GOOGLE_AI_KEY = process.env.GOOGLE_AI_KEY || process.env.VITE_GOOGLE_AI_KEY || process.env.google_ai_key || '';
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY || process.env.VITE_OPENROUTER_API_KEY || process.env.openrouter_api_key || '';

// Debug logging
console.log('AI Routes - Environment check:');
console.log('  KIMI_API_KEY exists:', !!KIMI_API_KEY, 'Length:', KIMI_API_KEY.length);
console.log('  GOOGLE_AI_KEY exists:', !!GOOGLE_AI_KEY, 'Length:', GOOGLE_AI_KEY.length);
console.log('  OPENROUTER_API_KEY exists:', !!OPENROUTER_API_KEY, 'Length:', OPENROUTER_API_KEY.length);
if (!KIMI_API_KEY) console.log('  WARNING: KIMI_API_KEY not set');
if (!GOOGLE_AI_KEY) console.log('  WARNING: GOOGLE_AI_KEY not set');
if (!OPENROUTER_API_KEY) console.log('  WARNING: OPENROUTER_API_KEY not set');

// Legal disclaimer to be included in all analyses
const LEGAL_DISCLAIMER = `
LEGAL DISCLAIMER: This analysis is generated by artificial intelligence for educational purposes only and does not constitute financial advice, investment recommendations, or solicitation to trade. Trading forex, commodities, and indices carries substantial risk of loss. Past performance does not guarantee future results. Always conduct your own research and consult a qualified financial advisor before making any trading decisions. The AI Trade Assistant and Golden Passage platform are not responsible for any trading losses incurred.`;

// Demo mode - generates realistic analysis without APIs
function generateDemoAnalysis(instrument: string, tradeType: string): AIAnalysis {
  const currentDate = new Date().toISOString().split('T')[0];
  const currentTime = new Date().toLocaleTimeString('en-US', { 
    hour: '2-digit', 
    minute: '2-digit', 
    timeZone: 'America/New_York' 
  });
  
  const basePrices: { [key: string]: number } = {
    'EUR/USD': 1.0850, 'GBP/USD': 1.2650, 'USD/JPY': 148.50,
    'USD/CHF': 0.8850, 'AUD/USD': 0.6550, 'NZD/USD': 0.5950,
    'USD/CAD': 1.3650, 'EUR/GBP': 0.8570, 'GBP/JPY': 187.50,
    'EUR/JPY': 161.20, 'XAU/USD': 2035.50, 'XAG/USD': 22.85,
    'USOIL': 73.50, 'ES': 4950.00, 'NQ': 17650.00,
    'YM': 38650.00, 'HSI': 16500.00
  };
  
  const basePrice = basePrices[instrument] || 100.00;
  const pipSize = instrument.includes('JPY') ? 0.01 : 
                  instrument.includes('XAU') ? 0.1 : 
                  instrument.includes('XAG') ? 0.01 : 
                  instrument.includes('ES') || instrument.includes('NQ') || 
                  instrument.includes('YM') || instrument.includes('HSI') ? 1 : 0.0001;
  const pipValue = pipSize * 100;
  
  const entryZone = `${(basePrice - pipValue * 0.5).toFixed(4)} - ${(basePrice + pipValue * 0.5).toFixed(4)}`;
  const stopLoss = (basePrice - pipValue * 2).toFixed(4);
  const takeProfit1 = (basePrice + pipValue * 3).toFixed(4);
  const takeProfit2 = (basePrice + pipValue * 5).toFixed(4);
  
  const analyses: { [key: string]: { fundamental: string; technical: string; context: string } } = {
    'EUR/USD': {
      context: 'EUR/USD is trading within yesterday\'s range, respecting the Asian session consolidation. Price is approaching a key order block on the 4H timeframe.',
      fundamental: 'DXY showing weakness after Fed comments. Euro supported by better-than-expected EU inflation data. ECB maintains hawkish stance. Watch for US NFP data impact.',
      technical: 'Daily trend is bullish with HH/HL structure. Price mitigated a bullish order block at 1.0820 and bounced. Resistance at 1.0900 (previous day high), support at 1.0800. Look for FVG fills on 15m for entries.'
    },
    'GBP/USD': {
      context: 'Cable showing strength during London session. Price swept Asian session lows and reversed with momentum.',
      fundamental: 'BoE maintaining higher rates than ECB providing sterling support. UK PMI data beat expectations. DXY weakness helping GBP pairs across the board.',
      technical: 'Bullish structure on H4. Price formed a higher low at 1.2600. Key resistance at 1.2700 (previous week high). Bearish FVG at 1.2630-1.2640 may act as support on retest.'
    },
    'USD/JPY': {
      context: 'USD/JPY consolidating near recent highs. Tokyo session showed indecision with inside bars forming.',
      fundamental: 'BOJ intervention threats capping upside. US-Japan rate differential still supporting USD. Risk-off flows could trigger yen strength quickly. Monitor 10-year yields.',
      technical: 'Strong uptrend but overextended on Daily. Key support at 147.00 (previous resistance turned support). Bearish order block at 149.00. Watch for liquidity sweep above 149.50 before potential reversal.'
    },
    'XAU/USD': {
      context: 'Gold trading near key psychological $2000 level. Safe-haven flows active amid geopolitical tensions.',
      fundamental: 'Gold supported by declining real yields and geopolitical risk premium. DXY weakness providing tailwind. Watch for Fed speaker comments that could impact rate expectations.',
      technical: 'Daily bullish with price above 20 EMA. Key support at $2015 (bullish order block). Resistance at $2050. Silver lagging gold - potential arbitrage opportunity. Look for entries near $2020-2025 zone.'
    }
  };
  
  const defaultAnalysis = {
    context: `${instrument} is consolidating during the current session. Price action shows indecision with reduced volatility. Key levels from Asian session remain respected.`,
    fundamental: `Monitor DXY direction for USD pairs. Check forexfactory.com for today's high-impact news. Current market sentiment is mixed with no clear catalyst.`,
    technical: `Mark previous day high/low as key levels. Identify order blocks on H4 timeframe. Wait for price to reach premium/discount zones before entering.`
  };
  
  const analysis = analyses[instrument] || defaultAnalysis;
  
  return {
    marketContext: `[DEMO MODE - ${currentDate} ${currentTime} EST] ${analysis.context}`,
    fundamentalBias: analysis.fundamental,
    technicalBias: analysis.technical,
    plan: `1. Wait for price to reach ${tradeType === 'Intraday' ? '15m/1H' : '4H/Daily'} premium/discount zone\n2. Look for liquidity sweep of Asian session highs/lows\n3. Confirm Market Structure Shift (MSS) on LTF\n4. Enter at Fair Value Gap or Order Block\n5. Target: ${takeProfit1} (1:1.5 RR) then ${takeProfit2}\n\n${LEGAL_DISCLAIMER}`,
    riskWarning: `[DEMO MODE - APIs unavailable] Always verify with your own analysis. Check forexfactory.com for news. Risk only 1-2% per trade.\n\n${LEGAL_DISCLAIMER}`,
    entryZone: entryZone,
    stopLoss: stopLoss,
    takeProfit: takeProfit1
  };
}

async function getKimiAnalysis(instrument: string, tradeType: string): Promise<AIAnalysis | null> {
  if (!KIMI_API_KEY) {
    console.log('No Kimi API key found in environment');
    return null;
  }

  try {
    console.log('Calling Kimi API for:', instrument);
    console.log('Using API key (first 20 chars):', KIMI_API_KEY.substring(0, 20) + '...');
    
    const response = await fetch('https://api.moonshot.cn/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${KIMI_API_KEY}`
      },
      body: JSON.stringify({
        model: 'kimi-latest',
        messages: [
          { 
            role: 'system', 
            content: 'You are a professional trading analyst with 20+ years of institutional trading experience.'
          },
          { 
            role: 'user', 
            content: `Analyze ${instrument} for ${tradeType} trading.

Provide analysis in this EXACT format:

MARKET_CONTEXT: Current price action and trend
FUNDAMENTAL_BIAS: DXY, interest rates, and macro factors  
TECHNICAL_BIAS: Daily/4H trend, support/resistance, order blocks
THE_PLAN:
- Entry Zone: Price range
- Stop Loss: Logical level
- Take Profit 1: First target
RISK_WARNING: Key risks to watch. Include this legal disclaimer: "This analysis is for educational purposes only and does not constitute financial advice. Trading carries substantial risk."

Be specific with price levels.`
          }
        ],
        temperature: 0.3,
        max_tokens: 1500
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Kimi API failed:', response.status, errorText);
      return null;
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content || '';
    
    if (!content || content.length < 50) {
      console.log('Kimi response too short');
      return null;
    }

    // Parse the response
    const contextMatch = content.match(/MARKET_CONTEXT:\s*([^]*?)(?=FUNDAMENTAL_BIAS:|$)/i);
    const fundamentalMatch = content.match(/FUNDAMENTAL_BIAS:\s*([^]*?)(?=TECHNICAL_BIAS:|$)/i);
    const technicalMatch = content.match(/TECHNICAL_BIAS:\s*([^]*?)(?=THE_PLAN:|$)/i);
    const planMatch = content.match(/THE_PLAN:\s*([^]*?)(?=RISK_WARNING:|$)/i);
    const riskMatch = content.match(/RISK_WARNING:\s*([^]*?)$/i);
    
    const entryMatch = content.match(/Entry Zone:\s*([\d.,\s\-/~]+)/i) || content.match(/Entry:\s*([\d.,\s\-/~]+)/i);
    const stopMatch = content.match(/Stop Loss:\s*([\d.,\s\-/~]+)/i) || content.match(/Stop:\s*([\d.,\s\-/~]+)/i);
    const tpMatch = content.match(/Take Profit 1:\s*([\d.,\s\-/~]+)/i) || content.match(/TP1:\s*([\d.,\s\-/~]+)/i);

    console.log('Kimi API success for:', instrument);
    
    return {
      marketContext: contextMatch?.[1]?.trim() || `${instrument} analysis`,
      fundamentalBias: fundamentalMatch?.[1]?.trim() || 'Check DXY and news',
      technicalBias: technicalMatch?.[1]?.trim() || 'Mark S/R levels manually',
      plan: planMatch?.[1]?.trim() || 'Follow your strategy',
      riskWarning: riskMatch?.[1]?.trim() || 'Risk 1-2% per trade',
      entryZone: entryMatch?.[1]?.trim() || 'See technical analysis',
      stopLoss: stopMatch?.[1]?.trim() || 'Below structure',
      takeProfit: tpMatch?.[1]?.trim() || 'Next S/R level'
    };
  } catch (error) {
    console.error('Kimi error:', error);
    return null;
  }
}

async function getGoogleAnalysis(instrument: string, tradeType: string): Promise<AIAnalysis | null> {
  if (!GOOGLE_AI_KEY) {
    console.log('No Google API key found in environment');
    return null;
  }

  try {
    console.log('Calling Google Gemini API for:', instrument);
    
    // Try different model names as they change frequently
    const models = ['gemini-1.5-flash-latest', 'gemini-1.5-flash', 'gemini-pro'];
    
    for (const model of models) {
      try {
        console.log(`Trying model: ${model}`);
        const response = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GOOGLE_AI_KEY}`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              contents: [{ 
                parts: [{ 
                  text: `As an expert institutional trader, analyze ${instrument} for ${tradeType} trading.

Format:
MARKET_CONTEXT: Current price action
FUNDAMENTAL_BIAS: Macro drivers
TECHNICAL_BIAS: Levels and structure
THE_PLAN: Entry, stop, targets
RISK_WARNING: Key risks

Use exact format with colons.` 
                }] 
              }],
              generationConfig: { temperature: 0.3, maxOutputTokens: 1500 }
            })
          }
        );

        if (!response.ok) {
          const errorText = await response.text();
          console.error(`Google API (${model}) failed:`, response.status, errorText);
          continue; // Try next model
        }

        const data = await response.json();
        const content = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
        
        if (!content || content.length < 50) {
          console.log(`Google API (${model}) response too short`);
          continue;
        }

        console.log(`Google API (${model}) success!`);

        const contextMatch = content.match(/MARKET_CONTEXT:\s*([^]*?)(?=FUNDAMENTAL_BIAS:|$)/i);
        const fundamentalMatch = content.match(/FUNDAMENTAL_BIAS:\s*([^]*?)(?=TECHNICAL_BIAS:|$)/i);
        const technicalMatch = content.match(/TECHNICAL_BIAS:\s*([^]*?)(?=THE_PLAN:|$)/i);
        const planMatch = content.match(/THE_PLAN:\s*([^]*?)(?=RISK_WARNING:|$)/i);
        const riskMatch = content.match(/RISK_WARNING:\s*([^]*?)$/i);
        
        const entryMatch = content.match(/Entry Zone:\s*([\d.,\s\-/~]+)/i) || content.match(/Entry:\s*([\d.,\s\-/~]+)/i);
        const stopMatch = content.match(/Stop Loss:\s*([\d.,\s\-/~]+)/i) || content.match(/Stop:\s*([\d.,\s\-/~]+)/i);
        const tpMatch = content.match(/Take Profit 1:\s*([\d.,\s\-/~]+)/i) || content.match(/TP1:\s*([\d.,\s\-/~]+)/i);

        return {
          marketContext: contextMatch?.[1]?.trim() || `${instrument} analysis`,
          fundamentalBias: fundamentalMatch?.[1]?.trim() || 'Check DXY and news',
          technicalBias: technicalMatch?.[1]?.trim() || 'Mark S/R levels manually',
          plan: planMatch?.[1]?.trim() || 'Follow your strategy',
          riskWarning: riskMatch?.[1]?.trim() || 'Risk 1-2% per trade',
          entryZone: entryMatch?.[1]?.trim() || 'See technical analysis',
          stopLoss: stopMatch?.[1]?.trim() || 'Below structure',
          takeProfit: tpMatch?.[1]?.trim() || 'Next S/R level'
        };
      } catch (modelError) {
        console.error(`Google API (${model}) error:`, modelError);
        continue;
      }
    }
    
    console.log('All Google models failed');
    return null;
  } catch (error) {
    console.error('Google error:', error);
    return null;
  }
}

// Professional Trading Analyst System Prompt
const TRADING_SYSTEM_PROMPT = `You are an elite institutional trading analyst with 20+ years of experience at top-tier investment banks and hedge funds. Your expertise spans:

- ICT (Inner Circle Trader) methodology and Smart Money Concepts
- Order Flow Analysis and Market Structure
- Multi-timeframe Analysis (Monthly/Daily/4H/1H)
- Risk Management and Position Sizing
- Macro-economic fundamentals and intermarket analysis
- Price Action and Volume Profile

When analyzing trading instruments:
1. Identify the current market structure (trending/ranging)
2. Mark key liquidity levels and order blocks
3. Analyze DXY correlation for USD pairs
4. Provide specific, actionable price levels
5. Include risk warnings and position sizing guidance
6. Consider high-impact news events

Be precise with price levels and always emphasize risk management.

IMPORTANT: At the end of every RISK_WARNING section, include this exact legal disclaimer:
"LEGAL DISCLAIMER: This analysis is generated by artificial intelligence for educational purposes only and does not constitute financial advice, investment recommendations, or solicitation to trade. Trading forex, commodities, and indices carries substantial risk of loss. Past performance does not guarantee future results. Always conduct your own research and consult a qualified financial advisor before making any trading decisions. The AI Trade Assistant and Golden Passage platform are not responsible for any trading losses incurred."`;

async function getOpenRouterAnalysis(instrument: string, tradeType: string): Promise<AIAnalysis | null> {
  if (!OPENROUTER_API_KEY) {
    console.log('No OpenRouter API key found in environment');
    return null;
  }

  try {
    console.log('Calling OpenRouter API for:', instrument);
    
    // Create an AbortController for timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 15000); // 15 second timeout
    
    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      signal: controller.signal,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
        'HTTP-Referer': 'https://golden-passage.com',
        'X-Title': 'Golden Passage Trading Platform'
      },
      body: JSON.stringify({
        model: 'qwen/qwen3-coder-next',
        messages: [
          { 
            role: 'user', 
            content: `${TRADING_SYSTEM_PROMPT}

---

Analyze ${instrument} for ${tradeType} trading.

Provide a comprehensive trading analysis in this EXACT format:

MARKET_CONTEXT: 
- Current price action and session context
- Key levels from Asian/London/NY sessions
- Overall trend structure (bullish/bearish/ranging)

FUNDAMENTAL_BIAS:
- DXY direction and impact
- Relevant central bank policies (Fed/ECB/BoE/BoJ)
- High-impact news events to watch
- Risk sentiment (risk-on/risk-off)

TECHNICAL_BIAS:
- Daily/4H trend analysis
- Key support/resistance levels with specific prices
- Order blocks and fair value gaps
- Liquidity pools above/below current price

THE_PLAN:
- Entry Zone: Specific price range for entry
- Stop Loss: Logical invalidation level
- Take Profit 1: First target (1.5-2 R:R)
- Take Profit 2: Extended target
- Entry criteria: What to wait for before entering

RISK_WARNING:
- Key risks for this setup
- Recommended position size (max 1-2% risk)
- News events that could invalidate the trade

Be specific with exact price levels for ${instrument}.` 
          }
        ],
        temperature: 0.2,
        max_tokens: 2000
      })
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errorText = await response.text();
      console.error('OpenRouter API failed:', response.status, errorText);
      return null;
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content || '';
    
    if (!content || content.length < 100) {
      console.log('OpenRouter response too short');
      return null;
    }

    console.log('OpenRouter API success!');

    // Parse the response
    const contextMatch = content.match(/MARKET_CONTEXT:\s*([^]*?)(?=FUNDAMENTAL_BIAS:|$)/i);
    const fundamentalMatch = content.match(/FUNDAMENTAL_BIAS:\s*([^]*?)(?=TECHNICAL_BIAS:|$)/i);
    const technicalMatch = content.match(/TECHNICAL_BIAS:\s*([^]*?)(?=THE_PLAN:|$)/i);
    const planMatch = content.match(/THE_PLAN:\s*([^]*?)(?=RISK_WARNING:|$)/i);
    const riskMatch = content.match(/RISK_WARNING:\s*([^]*?)$/i);
    
    const entryMatch = content.match(/Entry Zone:\s*([\d.,\s\-/~]+)/i) || content.match(/Entry:\s*([\d.,\s\-/~]+)/i);
    const stopMatch = content.match(/Stop Loss:\s*([\d.,\s\-/~]+)/i) || content.match(/Stop:\s*([\d.,\s\-/~]+)/i);
    const tpMatch = content.match(/Take Profit 1:\s*([\d.,\s\-/~]+)/i) || content.match(/TP1:\s*([\d.,\s\-/~]+)/i);

    return {
      marketContext: contextMatch?.[1]?.trim() || `${instrument} analysis via OpenRouter`,
      fundamentalBias: fundamentalMatch?.[1]?.trim() || 'Monitor DXY and news',
      technicalBias: technicalMatch?.[1]?.trim() || 'Mark S/R levels manually',
      plan: planMatch?.[1]?.trim() || 'Follow your strategy',
      riskWarning: riskMatch?.[1]?.trim() || 'Risk 1-2% per trade',
      entryZone: entryMatch?.[1]?.trim() || 'See technical analysis',
      stopLoss: stopMatch?.[1]?.trim() || 'Below structure',
      takeProfit: tpMatch?.[1]?.trim() || 'Next S/R level'
    };
  } catch (error: any) {
    if (error.name === 'AbortError') {
      console.error('OpenRouter API timed out after 15 seconds');
    } else {
      console.error('OpenRouter error:', error);
    }
    return null;
  }
}

/**
 * @swagger
 * /api/v1/ai/analyze:
 *   post:
 *     summary: Analyze trading instrument with AI
 *     tags: [AI]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - instrument
 *             properties:
 *               instrument:
 *                 type: string
 *                 example: EUR/USD
 *               tradeType:
 *                 type: string
 *                 example: Intraday
 *     responses:
 *       200:
 *         description: AI analysis result
 *       400:
 *         description: Missing instrument
 */
router.post('/analyze', async (req: Request, res: Response) => {
  const { instrument, tradeType = 'Intraday' } = req.body;
  
  if (!instrument) {
    return res.status(400).json({ error: 'Instrument is required' });
  }

  console.log(`AI analyze request: ${instrument} (${tradeType})`);
  console.log('API Keys status:', {
    google: !!GOOGLE_AI_KEY,
    kimi: !!KIMI_API_KEY,
    openrouter: !!OPENROUTER_API_KEY
  });
  
  // Try Google first (priority #1)
  let analysis = await getGoogleAnalysis(instrument, tradeType);
  let source = 'google';
  
  // Try Kimi if Google failed
  if (!analysis) {
    console.log('Google failed, trying Kimi...');
    analysis = await getKimiAnalysis(instrument, tradeType);
    source = 'kimi';
  }
  
  // Try OpenRouter if Kimi failed
  if (!analysis) {
    console.log('Kimi failed, trying OpenRouter...');
    analysis = await getOpenRouterAnalysis(instrument, tradeType);
    source = 'openrouter';
  }
  
  // Use demo mode if all APIs failed
  if (!analysis) {
    console.log('All APIs failed, using demo mode...');
    analysis = generateDemoAnalysis(instrument, tradeType);
    source = 'demo';
  }
  
  res.json({
    success: true,
    source,
    analysis
  });
});

/**
 * @swagger
 * /api/v1/ai/analyze-setup:
 *   post:
 *     summary: Analyze trading setup (alias for /analyze)
 *     tags: [AI]
 */
router.post('/analyze-setup', async (req: Request, res: Response) => {
  const { instrument, tradeType = 'Intraday' } = req.body;
  
  if (!instrument) {
    return res.status(400).json({ error: 'Instrument is required' });
  }

  console.log(`AI analyze request: ${instrument} (${tradeType})`);
  
  // Try Google first (priority #1)
  let analysis = await getGoogleAnalysis(instrument, tradeType);
  let source = 'google';
  
  // Try Kimi if Google failed
  if (!analysis) {
    console.log('Google failed, trying Kimi...');
    analysis = await getKimiAnalysis(instrument, tradeType);
    source = 'kimi';
  }
  
  // Try OpenRouter if Kimi failed
  if (!analysis) {
    console.log('Kimi failed, trying OpenRouter...');
    analysis = await getOpenRouterAnalysis(instrument, tradeType);
    source = 'openrouter';
  }
  
  // Use demo mode if all APIs failed
  if (!analysis) {
    console.log('All APIs failed, using demo mode...');
    analysis = generateDemoAnalysis(instrument, tradeType);
    source = 'demo';
  }
  
  res.json({
    success: true,
    source,
    analysis
  });
});

/**
 * @swagger
 * /api/v1/ai/daily-strategy:
 *   post:
 *     summary: Generate AI daily strategy
 *     tags: [AI]
 */
/**
 * @swagger
 * /api/v1/ai/test:
 *   get:
 *     summary: Test AI APIs
 *     tags: [AI]
 */
router.get('/test', async (req: Request, res: Response) => {
  console.log('Testing AI APIs...');
  
  // Test each API
  const results = {
    google: { tested: false, working: false, error: null as string | null },
    kimi: { tested: false, working: false, error: null as string | null },
    openrouter: { tested: false, working: false, error: null as string | null },
  };
  
  // Test Google
  if (GOOGLE_AI_KEY) {
    results.google.tested = true;
    try {
      const googleResult = await getGoogleAnalysis('EUR/USD', 'Intraday');
      results.google.working = !!googleResult;
      if (!googleResult) results.google.error = 'Returned null';
    } catch (e: any) {
      results.google.error = e.message;
    }
  }
  
  // Test Kimi
  if (KIMI_API_KEY) {
    results.kimi.tested = true;
    try {
      const kimiResult = await getKimiAnalysis('EUR/USD', 'Intraday');
      results.kimi.working = !!kimiResult;
      if (!kimiResult) results.kimi.error = 'Returned null';
    } catch (e: any) {
      results.kimi.error = e.message;
    }
  }
  
  // Test OpenRouter
  if (OPENROUTER_API_KEY) {
    results.openrouter.tested = true;
    try {
      const orResult = await getOpenRouterAnalysis('EUR/USD', 'Intraday');
      results.openrouter.working = !!orResult;
      if (!orResult) results.openrouter.error = 'Returned null';
    } catch (e: any) {
      results.openrouter.error = e.message;
    }
  }
  
  res.json({
    env: {
      hasGoogleKey: !!GOOGLE_AI_KEY,
      hasKimiKey: !!KIMI_API_KEY,
      hasOpenRouterKey: !!OPENROUTER_API_KEY,
    },
    results,
    timestamp: new Date().toISOString()
  });
});

router.post('/daily-strategy', (req: Request, res: Response) => {
  res.json({
    strategy: {
      title: 'Trend Following Strategy',
      description: 'Follow the major trend with RSI confirmation',
      entryRules: ['Price above 50 EMA', 'RSI > 50'],
      exitRules: ['RSI > 70 (overbought)', 'Price crosses below 20 EMA']
    }
  });
});

export default router;
